// Generated by scripts/material-symbols.sh from server/testdata/app_icons.json - don't edit.
package com.kidslauncher.mdm.appdisplay

import com.kidslauncher.mdm.R

/** A tile colour: the seed the parent picked and [tile] = `tileColor(seed)` (ARGB). */
data class AppColor(val seed: Int, val tile: Int)

/**
 * The parent's icon and colour choices for an app (design 14): Material Symbols Rounded, filled
 * (Apache-2.0, `res/drawable/app_glyph_*.xml`), and the tile colours. `AppGlyphsTest` checks them
 * against `app_icons.json`.
 */
object AppGlyphs {
    /** Icon key -> its white glyph. */
    val ICONS: Map<String, Int> = linkedMapOf(
        "chat" to R.drawable.app_glyph_chat,
        "mail" to R.drawable.app_glyph_mail,
        "photo_camera" to R.drawable.app_glyph_photo_camera,
        "photo_library" to R.drawable.app_glyph_photo_library,
        "music_note" to R.drawable.app_glyph_music_note,
        "play_circle" to R.drawable.app_glyph_play_circle,
        "sports_esports" to R.drawable.app_glyph_sports_esports,
        "menu_book" to R.drawable.app_glyph_menu_book,
        "school" to R.drawable.app_glyph_school,
        "calculate" to R.drawable.app_glyph_calculate,
        "map" to R.drawable.app_glyph_map,
        "calendar_month" to R.drawable.app_glyph_calendar_month,
        "alarm" to R.drawable.app_glyph_alarm,
        "public" to R.drawable.app_glyph_public,
        "partly_cloudy_day" to R.drawable.app_glyph_partly_cloudy_day,
        "star" to R.drawable.app_glyph_star,
    )

    /** Icon key -> the Material Symbols name. */
    val SYMBOLS: Map<String, String> = linkedMapOf(
        "chat" to "chat",
        "mail" to "mail",
        "photo_camera" to "photo_camera",
        "photo_library" to "photo_library",
        "music_note" to "music_note",
        "play_circle" to "play_circle",
        "sports_esports" to "sports_esports",
        "menu_book" to "menu_book",
        "school" to "school",
        "calculate" to "calculate",
        "map" to "map",
        "calendar_month" to "calendar_month",
        "alarm" to "alarm",
        "public" to "public",
        "partly_cloudy_day" to "partly_cloudy_day",
        "star" to "star",
    )

    /** Colour key -> seed and tile. */
    val COLORS: Map<String, AppColor> = linkedMapOf(
        "peach" to AppColor(0xFFF0A884.toInt(), 0xFFE4763F.toInt()),
        "plum" to AppColor(0xFF4A2545.toInt(), 0xFF4A2545.toInt()),
        "sky" to AppColor(0xFF1C7ED6.toInt(), 0xFF1E7ED4.toInt()),
        "sunset" to AppColor(0xFFF76707.toInt(), 0xFFDE6C20.toInt()),
        "night" to AppColor(0xFF1C1A2A.toInt(), 0xFF1C1A2A.toInt()),
        "grey" to AppColor(0xFF868E96.toInt(), 0xFF868E96.toInt()),
    )
}
