#!/usr/bin/env python3
"""Generate the launcher's app icon and launch splash from the Vibb mark.

    python3 launcher/scripts/vibb-icon.py <path to palchrb/vibb checkout>

Source: pi/art/vibb-appikon-natt-skarp.svg in palchrb/vibb (Vibb mark (c) palchrb, see NOTICE.md)
- the SHARP artboard, since Android launchers mask the icon themselves. The rings are
hand-shaped polylines (the radius wanders ~4% around the turn), so their path data is copied as
is, not approximated. Writes, under launcher/app/src/main/res/drawable/:

- ic_launcher_foreground.xml - the adaptive icon's foreground (and themed/monochrome layer):
  the four rings (#f0a884, stroke 2.6) and the core (#fbe4dc), scaled into the 66 dp safe zone
  of the 108 dp canvas. The background is @color/vibb_night (#0c0c14).
- splash_vibb_breathe.xml - an AnimatedVectorDrawable for the Home splash: one "breath" of
  pi/art/vibb-logo-pust-240-natt.svg (rings scale 0.94 -> 1.04 and fade 0.55 -> 1, the outer ring
  first; core 0.9 -> 1.08), compressed from the 4 s loop to under 1000 ms. 288 dp canvas with
  the mark inside the 192 dp circle (SplashScreen API, icon without an icon background).
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DRAWABLE = os.path.join(os.path.dirname(HERE), "app", "src", "main", "res", "drawable")
RING = "#FFF0A884"
CORE = "#FFFBE4DC"
STROKE = "2.6"
# In the pust SVG each ring's breath starts this much earlier in its 4 s cycle (outer first).
LEADS_S = [0.84, 0.56, 0.28, 0.0]
SPLASH_MS = 1000
BREATH_MS = 790  # each ring's breath; the last starts 210 ms in, so all end by 1000 ms


def rings(svg_path):
    svg = open(svg_path, encoding="utf-8").read()
    paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
    core = float(re.search(r'<circle[^>]*\sr="([\d.]+)"', svg).group(1))
    reach = max(abs(float(v)) for d in paths for v in re.findall(r"-?[\d.]+", d)) + 1.3
    return paths, core, reach


def circle(r):
    return f"M{-r:.2f},0a{r:.2f},{r:.2f} 0,1 0,{2 * r:.2f},0a{r:.2f},{r:.2f} 0,1 0,{-2 * r:.2f},0Z"


HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by launcher/scripts/vibb-icon.py from palchrb/vibb pi/art (Vibb mark (c) palchrb,
     see NOTICE.md). Don't edit by hand. -->
"""


def foreground(paths, core, reach):
    scale = 31.0 / reach  # the outer ring's outer edge 31 dp from the centre (safe zone: 33)
    body = "".join(
        f'        <path android:pathData="{d}" android:strokeColor="{RING}" android:strokeWidth="{STROKE}" />\n'
        for d in paths
    )
    return HEADER + f"""<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <group android:translateX="54" android:translateY="54" android:scaleX="{scale:.4f}" android:scaleY="{scale:.4f}">
{body}        <path android:pathData="{circle(core)}" android:fillColor="{CORE}" />
    </group>
</vector>
"""


def splash(paths, core, reach):
    scale = 90.0 / reach  # inside the 192 dp circle of the 288 dp splash icon
    groups = []
    for i, d in enumerate(paths):
        groups.append(f"""        <group android:name="ring{i}" android:scaleX="0.94" android:scaleY="0.94">
            <path android:name="ring{i}_path" android:pathData="{d}" android:strokeColor="{RING}" android:strokeWidth="{STROKE}" android:strokeAlpha="0.55" />
        </group>
""")
    groups.append(f"""        <group android:name="core" android:scaleX="0.9" android:scaleY="0.9">
            <path android:pathData="{circle(core)}" android:fillColor="{CORE}" />
        </group>
""")
    targets = []
    interp = "@android:interpolator/accelerate_decelerate"
    for i in range(len(paths)):
        delay = round((LEADS_S[0] - LEADS_S[i]) / 4.0 * 1000)
        targets.append(f"""    <target android:name="ring{i}">
        <aapt:attr name="android:animation">
            <set>
                <objectAnimator android:propertyName="scaleX" android:valueFrom="0.94" android:valueTo="1.04" android:duration="{BREATH_MS}" android:startOffset="{delay}" android:interpolator="{interp}" />
                <objectAnimator android:propertyName="scaleY" android:valueFrom="0.94" android:valueTo="1.04" android:duration="{BREATH_MS}" android:startOffset="{delay}" android:interpolator="{interp}" />
            </set>
        </aapt:attr>
    </target>
    <target android:name="ring{i}_path">
        <aapt:attr name="android:animation">
            <objectAnimator android:propertyName="strokeAlpha" android:valueFrom="0.55" android:valueTo="1" android:duration="{BREATH_MS}" android:startOffset="{delay}" android:interpolator="{interp}" />
        </aapt:attr>
    </target>
""")
    targets.append(f"""    <target android:name="core">
        <aapt:attr name="android:animation">
            <set>
                <objectAnimator android:propertyName="scaleX" android:valueFrom="0.9" android:valueTo="1.08" android:duration="{SPLASH_MS}" android:interpolator="{interp}" />
                <objectAnimator android:propertyName="scaleY" android:valueFrom="0.9" android:valueTo="1.08" android:duration="{SPLASH_MS}" android:interpolator="{interp}" />
            </set>
        </aapt:attr>
    </target>
""")
    return HEADER + f"""<animated-vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
    <aapt:attr name="android:drawable">
        <vector
            android:width="288dp"
            android:height="288dp"
            android:viewportWidth="288"
            android:viewportHeight="288">
            <group android:translateX="144" android:translateY="144" android:scaleX="{scale:.4f}" android:scaleY="{scale:.4f}">
{"".join("    " + line + chr(10) for g in groups for line in g.rstrip(chr(10)).split(chr(10)))}            </group>
        </vector>
    </aapt:attr>
{"".join(targets)}</animated-vector>
"""


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    paths, core, reach = rings(os.path.join(sys.argv[1], "pi", "art", "vibb-appikon-natt-skarp.svg"))
    assert len(paths) == len(LEADS_S), "expected the four rings of the Vibb mark"
    with open(os.path.join(DRAWABLE, "ic_launcher_foreground.xml"), "w", encoding="utf-8") as f:
        f.write(foreground(paths, core, reach))
    with open(os.path.join(DRAWABLE, "splash_vibb_breathe.xml"), "w", encoding="utf-8") as f:
        f.write(splash(paths, core, reach))


if __name__ == "__main__":
    main()
