//! Generated by scripts/material-symbols.sh from testdata/app_icons.json - don't edit. The
//! parent's icon and colour choices for an app on the kid's launcher (design 14); the glyphs are
//! `static/app-icons/<key>.svg` (Material Symbols Rounded, filled, Apache-2.0).

/// Icon key -> Material Symbols name.
pub const ICONS: &[(&str, &str)] = &[
    ("chat", "chat"),
    ("mail", "mail"),
    ("photo_camera", "photo_camera"),
    ("photo_library", "photo_library"),
    ("music_note", "music_note"),
    ("play_circle", "play_circle"),
    ("sports_esports", "sports_esports"),
    ("menu_book", "menu_book"),
    ("school", "school"),
    ("calculate", "calculate"),
    ("map", "map"),
    ("calendar_month", "calendar_month"),
    ("alarm", "alarm"),
    ("public", "public"),
    ("partly_cloudy_day", "partly_cloudy_day"),
    ("star", "star"),
];

/// Colour key -> (seed, tile): the tile is the launcher's `tileColor(seed)`.
pub const COLORS: &[(&str, &str, &str)] = &[
    ("peach", "#F0A884", "#E4763F"),
    ("plum", "#4A2545", "#4A2545"),
    ("sky", "#1C7ED6", "#1E7ED4"),
    ("sunset", "#F76707", "#DE6C20"),
    ("night", "#1C1A2A", "#1C1A2A"),
    ("grey", "#868E96", "#868E96"),
];
