//! Generated by scripts/material-symbols.sh from testdata/music_icons.json - don't edit. The
//! parent's icon and colour choices for a music category (design 21); the glyphs are
//! `static/music-icons/<key>.svg` (Material Symbols Rounded, filled, Apache-2.0).

/// Icon key -> Material Symbols name.
pub const ICONS: &[(&str, &str)] = &[
    ("music_note", "music_note"),
    ("star", "star"),
    ("menu_book", "menu_book"),
    ("mic", "mic"),
    ("auto_stories", "auto_stories"),
    ("bedtime", "bedtime"),
    ("headphones", "headphones"),
    ("radio", "radio"),
    ("piano", "piano"),
    ("pets", "pets"),
    ("favorite", "favorite"),
    ("rocket_launch", "rocket_launch"),
];

/// Colour key -> the tile colour (white on it >= 3:1).
pub const COLORS: &[(&str, &str)] = &[
    ("rose", "#C24F7A"),
    ("gold", "#B08A2E"),
    ("terracotta", "#C2683F"),
    ("teal", "#2F7A6B"),
    ("indigo", "#3B4A8C"),
    ("purple", "#8A5A9E"),
    ("green", "#4E7A3A"),
    ("sky", "#1E7ED4"),
];
