#!/bin/sh
# The parent's app icons (design docs/design/14-app-display.md): Material Symbols Rounded, filled,
# 24 px, from google/material-design-icons pinned to one commit and checked by SHA-256 (Apache
# License 2.0, compatible with GPL-3.0). Run from the repository root after changing
# server/testdata/app_icons.json (a new icon also needs its hash below). Needs curl, sha256sum and
# python3. Writes:
#   launcher/app/src/main/res/drawable/app_glyph_<key>.xml   (Android vectors, white)
#   launcher/app/src/main/java/com/kidslauncher/mdm/apps/AppGlyphs.kt   (the launcher's table)
#   launcher/app/src/main/assets/licenses/Apache-2.0.txt
#   launcher/app/src/test/resources/app_icons.json   (copy of the server's)
#   server/static/app-icons/<key>.svg and LICENSE.txt   (the PWA's preview)
#   server/src/app_icons.rs   (the server's table)
# Every converted file says what it was converted from (Apache-2.0 §4(b)).
set -eu
COMMIT=737e3324305806514d7909874fa1818ae1808232
BASE="https://raw.githubusercontent.com/google/material-design-icons/$COMMIT"
LICENSE_SHA256=58d1e17ffe5109a7ae296caafcadfdbe6a7d176f0bc4ab01e12a689b0499d8bd

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# name sha256 (symbols/web/<name>/materialsymbolsrounded/<name>_fill1_24px.svg)
cat > "$work/hashes" <<'HASHES'
chat ac0e5b39cb2ee236b6bcb296b566376fa30a50ef2b4434c170f49dfff7c174c1
mail dfbbc2052a050c40acb282a2dc6e001fe3de775e6457b7e30b50f92fe990d50a
photo_camera 0cf0ef91a871a6832f63d7a1e5dd4c544dd6a59c7ff8fa7145502e5fc2934170
photo_library 50540e191b262b34d4ba4eecb28fb3d3c0542fdfb61b1ba801039dd9fe20483f
music_note 6678b23e4e6ef7e9d46362d9085d7e704eeda30adee2d7cb42a3930d3342b11a
play_circle a74a026d1331d38a020ddc573c0373e9df3dba2df44d6874dde41c3004681c1f
sports_esports ac20652b182bf7f5b45b2979a42381f487c291d94f04772f876f93b2d3e9d868
menu_book 5c777c23b8535d621de7d5c2edaed226613d5864b84e8e9118beac596e615e69
school 646355683fd4f5e651793944f437e638fb6838934eb948d422453b283ff4ef7a
calculate 30b1a7b139eadb0399036182f6de17ab1df0e0b897923d75b57d678b858f11cc
map 70e4fd49ccc2aee882fa0c0ba083852600fc23f1e72528df73343957d987c9b7
calendar_month 175e8905d380b73158673f4b22cb536513173a754725291119e99b7da1856fb5
alarm cf52ab6e68ad2b4fb9834538f768cd843a63e260403525bad913d0c1609291e1
public 5b8ad24e63e4a2f601728fe0e589df9ca943b813ad24a71635c803a677e1ecc0
partly_cloudy_day 4c0249ace5744a708b6e5494cca17b47000b4351bf19a24b8bb41dc6aa763cc7
star 513a0f450ac62c6bdc6c6cb8701896ea4ac7a82121b9e19cc52596fd7ce3b5fc
HASHES

while read -r name sha; do
    curl -sfL -o "$work/$name.svg" "$BASE/symbols/web/$name/materialsymbolsrounded/${name}_fill1_24px.svg"
    echo "$sha  $work/$name.svg" | sha256sum -c --quiet -
done < "$work/hashes"
curl -sfL -o "$work/LICENSE" "$BASE/LICENSE"
echo "$LICENSE_SHA256  $work/LICENSE" | sha256sum -c --quiet -

python3 - "$work" "$COMMIT" <<'PY'
import json, os, re, shutil, sys

work, commit = sys.argv[1], sys.argv[2]
table = json.load(open("server/testdata/app_icons.json"))
icons, colors = table["icons"], table["colors"]
source = f"google/material-design-icons at {commit[:12]}"

os.makedirs("server/static/app-icons", exist_ok=True)
os.makedirs("launcher/app/src/main/assets/licenses", exist_ok=True)

for key, name in icons.items():
    svg = open(os.path.join(work, f"{name}.svg")).read()
    if 'viewBox="0 -960 960 960"' not in svg:
        sys.exit(f"{name}: unexpected viewBox")
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if len(paths) != 1:
        sys.exit(f"{name}: expected one path, found {len(paths)}")
    d = paths[0]
    note = (f'Converted from Material Symbols "{name}" (Rounded, filled, 24 px; {source}), '
            "Apache License 2.0")
    with open(f"launcher/app/src/main/res/drawable/app_glyph_{key}.xml", "w") as out:
        out.write('<?xml version="1.0" encoding="utf-8"?>\n'
                  f"<!-- {note} (assets/licenses/Apache-2.0.txt).\n"
                  "     Changed: SVG to an Android vector, white fill. Generated by scripts/material-symbols.sh. -->\n"
                  '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
                  '    android:width="24dp"\n    android:height="24dp"\n'
                  '    android:viewportWidth="960"\n    android:viewportHeight="960">\n'
                  '    <group android:translateY="960">\n'
                  f'        <path\n            android:fillColor="#FFFFFFFF"\n            android:pathData="{d}" />\n'
                  "    </group>\n</vector>\n")
    with open(f"server/static/app-icons/{key}.svg", "w") as out:
        out.write(f"<!-- {note} (LICENSE.txt). Changed: white fill. Generated by scripts/material-symbols.sh. -->\n"
                  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" width="24" height="24">'
                  f'<path fill="#fff" d="{d}"/></svg>\n')

shutil.copy(os.path.join(work, "LICENSE"), "launcher/app/src/main/assets/licenses/Apache-2.0.txt")
shutil.copy(os.path.join(work, "LICENSE"), "server/static/app-icons/LICENSE.txt")
shutil.copy("server/testdata/app_icons.json", "launcher/app/src/test/resources/app_icons.json")

def argb(hex_rgb):
    return "0xFF" + hex_rgb.lstrip("#").upper()

with open("launcher/app/src/main/java/com/kidslauncher/mdm/apps/AppGlyphs.kt", "w") as out:
    out.write("// Generated by scripts/material-symbols.sh from server/testdata/app_icons.json - don't edit.\n"
              "package com.kidslauncher.mdm.apps\n\n"
              "import com.kidslauncher.mdm.R\n\n"
              "/** A tile colour: the seed the parent picked and [tile] = `tileColor(seed)` (ARGB). */\n"
              "data class AppColor(val seed: Int, val tile: Int)\n\n"
              "/**\n * The parent's icon and colour choices for an app (design 14): Material Symbols Rounded, filled\n"
              " * (Apache-2.0, `res/drawable/app_glyph_*.xml`), and the tile colours. `AppGlyphsTest` checks them\n"
              " * against `app_icons.json`.\n */\n"
              "object AppGlyphs {\n"
              "    /** Icon key -> its white glyph. */\n"
              "    val ICONS: Map<String, Int> = linkedMapOf(\n")
    for key in icons:
        out.write(f'        "{key}" to R.drawable.app_glyph_{key},\n')
    out.write("    )\n\n    /** Icon key -> the Material Symbols name. */\n"
              "    val SYMBOLS: Map<String, String> = linkedMapOf(\n")
    for key, name in icons.items():
        out.write(f'        "{key}" to "{name}",\n')
    out.write("    )\n\n    /** Colour key -> seed and tile. */\n"
              "    val COLORS: Map<String, AppColor> = linkedMapOf(\n")
    for key, c in colors.items():
        out.write(f'        "{key}" to AppColor({argb(c["seed"])}.toInt(), {argb(c["tile"])}.toInt()),\n')
    out.write("    )\n}\n")

with open("server/src/app_icons.rs", "w") as out:
    out.write("//! Generated by scripts/material-symbols.sh from testdata/app_icons.json - don't edit. The\n"
              "//! parent's icon and colour choices for an app on the kid's launcher (design 14); the glyphs are\n"
              "//! `static/app-icons/<key>.svg` (Material Symbols Rounded, filled, Apache-2.0).\n\n"
              "/// Icon key -> Material Symbols name.\n"
              "pub const ICONS: &[(&str, &str)] = &[\n")
    for key, name in icons.items():
        out.write(f'    ("{key}", "{name}"),\n')
    out.write("];\n\n/// Colour key -> (seed, tile): the tile is the launcher's `tileColor(seed)`.\n"
              "pub const COLORS: &[(&str, &str, &str)] = &[\n")
    for key, c in colors.items():
        out.write(f'    ("{key}", "{c["seed"]}", "{c["tile"]}"),\n')
    out.write("];\n")
PY
echo "Done: $(python3 -c 'import json; print(len(json.load(open("server/testdata/app_icons.json"))["icons"]))') icons."
